### PR TITLE
Created an Anti-Mod System For those who want to 'cheat'

### PR DESCRIPTION
**Pull request by Jsa010**
Title Says It

### CODE REVIEW

**Comment by Jsa010** [comment]
> Cool concept, but not really serve's a purpose.

is just like the bob mod man

**Comment by Jsa010** [comment]
> Yeah, I can understand. (And i am 100% sure you hate me after ghost cycba drama)

nah man i don't hate you

**Comment by Jsa010** [comment]
> > > Yeah, I can understand. (And i am 100% sure you hate me after ghost cycba drama)
> > 
> > 
> > nah man i don't hate you
> 
> But, yeah whatever. Just I hate those cycba white-knight's (Including @Theoyeah himself)

that's ok

**Comment by EIT0** [comment]
Not useful, but going to implement the idea

**Comment by Jsa010** [comment]
> Not useful, but going to implement the idea

wdym with 'implement the idea'?

**Comment by EIT0** [comment]
> > Not useful, but going to implement the idea
> 
> wdym with 'implement the idea'?

Going to make an actual anti-cheat

**Pull request closed without merging**
