### PR TITLE
added that funny engine name like bambi purgatory!

### PR DESCRIPTION
**Pull request by REALHaydenGaming**
i am so sorry @EIT0, not sorry.
Just want to make psych tutorials a bit better :D

### CODE REVIEW

**Comment by REALHaydenGaming** [comment]
Might add that as an option, i am worried that it will break the game 😨 🔥

**Review by EIT0 — CHANGES_REQUESTED** [review]
the line:
"" + fuckEngine " Engine v" + psychEngineVersion
should be:
fuckEngine + "Engine v:" + psychEngineVersion

**Comment by REALHaydenGaming** [comment]
Oh, i only took some of the sources from the beta version of bp

**Comment by REALHaydenGaming** [comment]
Plus the space on that wouldn't fuck it, the typing

**Comment by REALHaydenGaming** [comment]
guess i'ma add some changes to it

**Comment by REALHaydenGaming** [comment]
If your wondering why there is 2 space's, it is so it doesn't fuck up the typing

**Comment by EIT0** [comment]
merged now

**Comment by REALHaydenGaming** [comment]
Remind me if there is any issues atm

**Comment by EIT0** [comment]
there are no issues

**Comment by REALHaydenGaming** [comment]
Less goooooo

**Pull request merged**
