### PR TITLE
Hola

### PR DESCRIPTION
**Pull request by Iamsamsmich6**
Hoal

### CODE REVIEW

**Comment by REALHaydenGaming** [comment]
K y and s
go fuck yourself, if you think saying "Hey daddy" to a damn minor?

**Comment by EIT0** [comment]
> K y and s go fuck yourself, if you think saying "Hey daddy" to a damn minor?

whar

**Comment by REALHaydenGaming** [comment]
i know Spanish, it exactly translates to what i said in that comment

**Comment by EIT0** [comment]
> i know Spanish, it exactly translates to what i said in that comment

But I never told so to a Minor + I am a minor

**Comment by REALHaydenGaming** [comment]
???? I was commenting on @Iamsamsmich6

**Comment by EIT0** [comment]
> 

ohhh. i was worried man

**Pull request closed without merging**
