### PR TITLE
fuck yeah memory peak & show memory for client

### PR DESCRIPTION
**Pull request by REALHaydenGaming**

### CODE REVIEW

**Comment by REALHaydenGaming** [comment]
????? Why close it?

**Comment by EIT0** [comment]
accidentally closed it :(

**Comment by REALHaydenGaming** [comment]
holy shit, that got merged, LESS GOOOOO (btw, i do know how to change fps fonts)

**Comment by REALHaydenGaming** [comment]
if you wish to make me help u, with more stuff, hit me up on newgrounds (there is a msg button)
haydengaming.newgrounds.com

**Comment by EIT0** [comment]
> if you wish to make me help u, with more stuff, hit me up on newgrounds (there is a msg button) haydengaming.newgrounds.com

sure man, since i will stop making tutorials frequently, you could help making some mini tutorials here

**Comment by REALHaydenGaming** [comment]
Yep, alright

**Comment by REALHaydenGaming** [comment]
making a sub playlist on my channel

**Comment by EIT0** [comment]
> making a sub playlist on my channel

could you send me your channel?

**Comment by REALHaydenGaming** [comment]
https://www.youtube.com/channel/UCdutVAjvzZgiK2j3gVXJ42Q

**Comment by EIT0** [comment]
thanks

**Pull request merged**
